#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#
# Actions
#
event_actions("nethserver-moodle-update", qw(
    initialize-default-databases 00
    nethserver-moodle-conf 20
));
event_actions("nethserver-moodle-save", qw(
));
event_actions("interface-update", qw(
));

#
# Templates
#
event_templates("nethserver-moodle-update", qw(
    /etc/httpd/conf.d/default-virtualhost.inc
    /etc/httpd/conf.d/moodle.conf
    /var/www/moodle/web/config.php
));
event_templates("certificate-update", qw(
    /etc/httpd/conf.d/moodle.conf
));
event_templates("certificate-upload", qw(
    /etc/httpd/conf.d/moodle.conf
));
event_templates("nethserver-letsencrypt-update", qw(
    /etc/httpd/conf.d/moodle.conf
));

#
# Services
#
event_services("nethserver-moodle-update", qw(
    httpd restart
));
